# specify the node base image with your desired version node:<version>
FROM node:11

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get upgrade -y
RUN apt-get install libpcap-dev -y
RUN npm install

# Make port 3001 available to the world outside this container
EXPOSE 3001

CMD npm run start-attacker
