version: '3.4'
services:
  nginxproxy:
    container_name: nginxProxy
    build:
      context: ./nginxProxy/
    ports: 
      - "80:80"
      - "443:443"
    volumes: 
      - ./sites/:/var/www/
      - ./nginxProxy/proxy/:/etc/nginx/conf.d/:ro
  coredns:
    container_name: coredns
    image: coredns/coredns
    command: -conf /root/Corefile 
    ports:
      - "192.168.8.101:53:53/udp"
      - "192.168.8.101:53:53"
    volumes:
      - ./coredns/:/root/
  chatbot:
    build:
      context: ./chatbot/
    ports:
      - "8080:8080"
      - "8081:8081"
  deepfake:
    build:
      context: ./deep-fake/
    ports:
      - "8082:8000"

